version: "3"
services:
    server:
      image: ecograd_server
      ports:
        - "5000:5000"
      environment:
        - DB_HOST=localhost
        - DB_PORT=5432
        - DB_USER=postgres
        - DB_PASSWORD=postgres
        - DB_SSL_MODE=disable
        - DB_NAME=gin_ecograd
