version: "3"
services:
    server:
        image: ecograd_server
        container_name: ecograd_server
        restart: always
        ports:
            - "5000:5000"
        environment:
          - APP_PORT=5000
          - APP_NAME=Ecograd
          - APP_DESCRIPTION=Ecograd
          - DB_HOST=localhost
          - DB_PORT=5432
          - DB_USER=admin
          - DB_PASSWORD=admin
          - DB_DATABASE=ecograd
          - PRIVATE_KEY=secret
