name: Manual workflow

on:
  push:
    branches: [ tmp ]
  pull_request:
    branches: [ tmp ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Release new version
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
                cd /opt/projects/ecograd
                git pull origin tmp
                docker-compose down
                docker build -t ecograd_server .
                docker-compose up -d
